global using Mapster;
global using MediatR;
global using Carter;
global using Marten;
global using BuildingBlocks.CQRS;
global using CatalogAPI.Models;
global using CatalogAPI.Exception;
global using FluentValidation;
global using BuildingBlocks.Helpers;